name: Deploy to Fly

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Fly GitHub Deploy
      uses: dentarg/fly@v1.2.1
      with:
        fly-token: ${{ vars.FLY_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
